services:
  - type: web
    name: selenium-server
    env: node
    buildCommand: 
      - npm install
      - pip install -r requirements.txt  # Install Python dependencies
    startCommand: npm start
